files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero:
    - 2
    - convention: '0'
  brace-style:
    - 2
    - allow-single-line: false
  extends-before-declarations: 0
  extends-before-mixins: 0
  leading-zero:
    - 2
    - include: true
  mixins-before-declarations: 0
  no-extends: 2
  no-qualifying-elements: 0
  property-sort-order: 0
  quotes:
    - 2
    - style: double

  class-name-format: 2
  function-name-format: 2
  id-name-format: 2
  mixin-name-format: 2
  placeholder-name-format: 2
  variable-name-format: 2